### ISSUE TITLE
Adressable 2.2.9 breaks

### ISSUE THREAD

**Issue by Xylakant** [Asquera/warden-hmac-authentication#18]
see https://github.com/sporkmonger/addressable/issues/77. Support for nested query parameters has been removed in 2.2.9, 2.2.8 is working just fine.

**Comment by gregory-m** [comment]
HI, can you please change add_runtime_dependency in gemspec, to require adressable 2.2.8.
Thanks

**Comment by Xylakant** [comment]
After merging this pull request I get local build failures, but travis seems to indicate everything is fine. So use with caution. I'll still close this issue for now and will investigate.
